### ISSUE TITLE
Download slows down after the first item of the queue is finished

### ISSUE THREAD

**Issue by acgonzales** [linuxwhatelse/pyloader#1]
It's all in the title, the first item in the queue downloads fast (normal speed). After the first one is finished, the succeeding items downloads slowly. The max_concurrent property is set to 1, the download is super slow if there are two or more concurrent downloads.

**Comment by tadly** [comment]
I've setup a simple test and while I do see differences, these don't seem to stem from pyloader itself as the results vary to much.
Mind giving this a shot as well and post the results?

What I did notice though is that **when** a download takes longer (like with Run 3 item1), it scales.
Initially I had a test with 500MB downloads rather then 50MB and if it happened to be a odd-ball, it would (as you mentioned) take significantly longer.
This could, for all I know, be related to python requests, my i-net connection or the server I'm downloading from.
I'll do some more testing when I find the time though.

Here's what I did:
```python
import time

import pyloader


def progress_callback(progress):
    print(progress.dlable.file_name, 'Time Spent:', progress.time_spent)
    return False


if __name__ == '__main__':
    loader = pyloader.Loader.get_loader()
    loader.configure(max_concurrent=1, update_interval=1,
                     progress_cb=progress_callback, daemon=False)
    loader.start()

    item1 = pyloader.DLable(url='http://download.thinkbroadband.com/50MB.zip',
                            target_dir='./', file_name='item1.zip')
    item2 = pyloader.DLable(url='http://download.thinkbroadband.com/50MB.zip',
                            target_dir='./', file_name='item2.zip')
    item3 = pyloader.DLable(url='http://download.thinkbroadband.com/50MB.zip',
                            target_dir='./', file_name='item3.zip')

    loader.queue(item1, 1)
    loader.queue(item2, 2)
    loader.queue(item3, 3)

    while loader.is_active():
        try:
            time.sleep(0.25)
        except KeyboardInterrupt:
            break

    loader.exit()
```

This gives me the following results for a few runs. (I manually formatted the output so it's not a huge wall of text)
```
# Run 1:
item3.zip Time Spent: 0.05831408500671387
...
item3.zip Time Spent: 11.063034772872925
---
item2.zip Time Spent: 0.06348180770874023
...
item2.zip Time Spent: 7.003448486328125
---
item1.zip Time Spent: 0.05950427055358887
...
item1.zip Time Spent: 11.528782606124878

# Run 2:
item3.zip Time Spent: 0.06509661674499512
...
item3.zip Time Spent: 8.852804899215698
---
item2.zip Time Spent: 0.09525728225708008
...
item2.zip Time Spent: 8.761652946472168
---
item1.zip Time Spent: 0.06193399429321289
...
item1.zip Time Spent: 10.521442651748657

# Run 3:
item3.zip Time Spent: 0.0679314136505127
...
item3.zip Time Spent: 5.482971668243408
---
item2.zip Time Spent: 0.058007240295410156
...
item2.zip Time Spent: 7.330093145370483
---
item1.zip Time Spent: 0.058913230895996094
...
item1.zip Time Spent: 16.38521933555603
```

**Comment by Chr1st-oo** [comment]
Mine had pretty close results. Maybe its just a problem with the server I'm downloading from.

item3.zip Time Spent: 56.170828342437744
...
item2.zip Time Spent: 51.66049551963806
...
item1.zip Time Spent: 51.979795694351196
